###

POST http://localhost:3333/api/v1/users/register HTTP/1.1
content-type: application/json

{
    "username":"James",
    "type":"admin",
    "email":"jamescog72@gmail.com",
    "password":"234354"
}


###
POST http://localhost:3333/api/v1/users/login HTTP/1.1
content-type: application/json

{
        "email":"jamescog72@gmail.com",
        "password":"234354"
}


###
POST http://localhost:3333/api/v1/logout HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6Ikhhd2kiLCJwYXNzd29yZCI6IiQyYiQxMCQ5NWUyZE45Q1BpcExSSWs1TE1hcFJlcncvdjBaNS9OUlNpSmUvWFhwMVBmMzA2NkxmZThKQyIsImVtYWlsIjoiamFtZXNjb2c3MkBnbWFpbC5jb20iLCJ0eXBlIjoiYWRtaW4iLCJjb25maXJtZWQiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjMtMDUtMjdUMTc6MTY6MDMuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjMtMDUtMjdUMTc6MTg6NTEuMDAwWiJ9LCJpYXQiOjE2ODUyMTU4MzksImV4cCI6MTY4NTgyMDYzOX0.-rYxnCmPEhA8J4Z45xTAB18-cR8eh1VtvrGX_TznKLE


### 
POST http://localhost:3333/api/v1/requestreset HTTP/1.1
content-type: application/json

{
    "email":"jamescog72@gmail.com"
}

### 
POST http://localhost:3333/api/v1/users/verifiedreset HTTP/1.1
Content-Type: application/json

{
    "email":"jamescog72@gmail.com",
    "password":"12345678"
}